version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  api_gateway:
    build:
      context: ./api_gateway
      dockerfile: Dockerfile.yml
    ports:
      - "3002:3002"
    depends_on:
      - user_service
      - venue_service

  user_service:
    build:
      context: ./user_service
      dockerfile: Dockerfile.yml
    depends_on:
      - postgres
      - rabbitmq

  venue_service:
    build:
      context: ./venue_service
      dockerfile: Dockerfile.yml
    depends_on:
      - postgres
      - rabbitmq

  booking_service:
    build:
      context: ./booking-service
      dockerfile: Dockerfile.yml
    depends_on:
      - postgres
      - rabbitmq


volumes:
  pg_data:
