version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - backend

  api_gateway:
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    depends_on:
      - user_service
      - venue_service
    networks:
      - backend

  user_service:
    build:
      context: ./user_service
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - backend

  venue_service:
    build:
      context: ./venue_service
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - backend

  booking_service:
    build:
      context: ./booking-service
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - backend

volumes:
  pg_data:

networks:
  backend:
